Rene
MercantecData/netvaerk-programmering-whitemangroup pull request #1
Opened 2019-12-10 08:39 UTC by shiome80

2019-12-10 09:47 UTC, MadsBock requested changes
Super godt, opgaverne er lavet. Prøv at gøre således at man kan skrive beskeder frem og tilbage kontinuerligt imellem de to programmer. Dvs. Client skriver, så skriver Server, så skriver Client. Hver gang så er det en ny besked der er blevet skrevet. Lidt ligesom et chatprogram.

2019-12-10 09:47 UTC, MadsBock commented on Opgave 2 - Call response/Opgave 2 - Call response/Program.cs
> +            IPAddress ip = IPAddress.Parse(EnterIp());
Hvad sker der hvis man skriver noget andet end en ip?

2019-12-10 09:53 UTC, shiome80 commented on Opgave 2 - Call response/Opgave 2 - Call response/Program.cs
> +            IPAddress ip = IPAddress.Parse(EnterIp());
Så crasher den fordi den ikke har korrekt error handling :D 
Det kigger jeg lige på

2019-12-11 08:26 UTC, merged

2019-12-11 08:26 UTC, shiome80 commented
Jeg har ikke kunne finde noget i debugging omkring hvad der sker på linje 89. Den stopper bare uden fejl, uden at kører ned i loopen

2019-12-11 09:22 UTC, MadsBock commented
Du må ikke selv merge ;)

> Den 11. dec. 2019 kl. 09.26 skrev shiome80 <notifications@github.com>:
> 
> Merged #1 <https://github.com/MercantecData/netvaerk-programmering-whitemangroup/pull/1> into master.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/MercantecData/netvaerk-programmering-whitemangroup/pull/1?email_source=notifications&email_token=ACCII2YAEYBCUM2WDGL2ALLQYCP2BA5CNFSM4JY2VCUKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVNB5S6Q#event-2873350522>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACCII23HTGHRWE7WPWRWE7DQYCP2BANCNFSM4JY2VCUA>.
>

2019-12-11 09:26 UTC, shiome80 commented
Da jeg trykkede "New pull request" gjorde den det selv. Jeg måtte hverken oprette ny branch eller request før den var merged

2019-12-11 09:27 UTC, MadsBock commented
Måtte du ikke oprette en ny branch?!

2019-12-11 09:28 UTC, MadsBock commented
Kig lige herned ved lejlighed. Har i øvrigt fundet dit problem med linje 89

2019-12-11 09:29 UTC, shiome80 commented
Den "nye" branch blev bare flettet sammen med den daværende branch fra igår